[package]
name = "veneer"
version = "0.1.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2"
sc = "0.2"
libc = {version = "0.2", default-features = false}
